[pytest]
addopts = -vs --html=./reports/login_report.html --self-contained-html
          --clean-alluredir --alluredir=reports/allure-results
testpaths = ./scripts
python_files = test_login_params_allure.py
python_classes = Test*
python_functions = test*